[project]
name = 'Tokenized-Tourism-Consciousness-Travel-Experiences'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.destination-integration]
path = 'contracts/destination-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.experience-design]
path = 'contracts/experience-design.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
